version: '3'

services:
  postgres:
    container_name: postgres-container
    image: postgres:12-alpine
    restart: always
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SCHEMA=crm
