version: '3'

services:
  crm: &db
    container_name: database-crm
    image: postgres:12-alpine
    restart: always
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=ecodados
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SCHEMA=crm

  specs:
    <<: *db
    container_name: database-specs
    ports:
      - '5433:5432'
